FROM php:8-apache

ARG USER_ID
ARG USER_NAME
ARG GROUP_ID
ARG GROUP_NAME
ARG COMPOSER_CACHE_DIR

ENV APACHE_RUN_USER=${USER_NAME}
ENV APACHE_RUN_GROUP=${GROUP_NAME}
ENV COMPOSER_CACHE_DIR=${COMPOSER_CACHE_DIR}

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
    curl \
    git \
    zip \
    unzip && \
    rm -rf /var/lib/apt/lists/*

RUN pecl channel-update pecl.php.net && \
    pecl install \
    xdebug

RUN docker-php-ext-install \
    pdo \
    pdo_mysql

RUN docker-php-ext-enable \
    xdebug

RUN a2enmod rewrite

COPY ./php.ini /usr/local/etc/php/
COPY ./xdebug.ini /usr/local/etc/php/conf.d/
COPY --from=composer /usr/bin/composer /usr/local/bin/composer

RUN groupadd --system --gid ${GROUP_ID} ${GROUP_NAME} && \
    useradd --system --shell /bin/bash --uid ${USER_ID} --gid ${GROUP_ID} ${USER_NAME} && \
    mkdir ${COMPOSER_CACHE_DIR} && \
    chown --recursive ${USER_ID}:${GROUP_ID} /var/www

USER ${USER_ID}:${GROUP_ID}